### ISSUE TITLE
Dynamic Weather "Main + DLC" position issue

### ISSUE THREAD

**Issue by aetonsi** [loot/fallout3#119]
Hello,
i'd like to report that the "Main + DLC merged" (crc `691323EB`) file of [Dynamic Weather](https://www.nexusmods.com/fallout3/mods/10607/) gets sorted **after** the mod's "addons".
It should be loaded before them all, instead.
I also checked with the standard "Main" file (without DLCs included) and that one is sorted correctly.
I checked the master list and it seems correct, though i have to admit i don't fully understand its structure...

From the mod's description (also the various ReadMe.txt confirm this):
> Example Load Order:
> 
> Fallout3.esm
> Anchorage.esm
> ThePitt.esm
> BrokenSteel.esm
> PointLookout.esm
> Zeta.esm
> ...
> Enhanced Weather - Rain and Snow.esm
> Xepha's Dynamic Weather.esm
> ...
> other Enhanced Weather - Rain and Snow.esp's
> ...
> **Xepha's Dynamic Weather - Main + DLC Merged.esp**
> Xepha's Dynamic Weather - Rain.esp
> Xepha's Dynamic Weather - Night Eye Edition Merged (NEE+OA+Rain).esp
> Xepha's Dynamic Weather - Dynamic Sneak Bonus.esp
> Xepha's Dynamic Weather - Sandstorms + Armor Damage (FOSE).esp
> Xepha's Dynamic Weather - Weather Machine ().esp

And this is what i get by sorting:
![image](https://user-images.githubusercontent.com/18366087/74146569-a418fa00-4c01-11ea-96e7-eca95580fdba.png)

**Comment by aetonsi** [comment]
Here's the "Main" file (without DLCs) sorted correctly:
![image](https://user-images.githubusercontent.com/18366087/74147330-44bbe980-4c03-11ea-90b6-aeb87f965da6.png)

**Comment by MacSplody** [comment]
@aetonsi It should sort correctly now. Thanks for reporting it.
