### ISSUE TITLE
The Mantis Imperative

### ISSUE THREAD

**Issue by Kelmych** [loot/fallout3#37]
The Mantis Imperative (http://www.nexusmods.com/fallout3/mods/12296)
The Mantis Imperative - Mantis.esp   CRC: 663DDF02   UDR:11   load before FO3 Wanderers Edition - Main File.esp
The Mantis Imperative - Nasty Zeta.esp CRC: BC544F07  ITM: 17
The Mantis Imperative - SkillBooks.esp  CRC: DD2E48B1  ITM: 1
The Mantis Imperative - Jello.esp  Bash Tags: Relev

**Comment by Ortham** [comment]
Closing this since the discussion was resolved.
