### ISSUE TITLE
Add a "Remove Cleaned ESMs before QuickAutoClean" message

### ISSUE THREAD

**Issue by Superfly-Johnson** [loot/fallout3#441]
Would have to find some way to check for the patched ESMs across versions but the patched ESMs consistently break quickautoclean. 

Went from 29 ITMs in TheInstitute to 1, among other issues.

**Comment by MacSplody** [comment]
A global message might be the best solution.

Something like 'Modified game ESMs detected, this can affect results when cleaning mods using xEdit.'
That might need some improvement in the wording.

The main issue is having a reliable way to check.
We could use the checksum of the updated files, or the base game files before and after cleaning.
Using the updated files is easier I think, though they may need to be updated, if the patcher is ever changed.

**Comment by pStyl3** [comment]
Can you explain the issue in more detail? What exactly do you mean by "patched ESMs"?

Do you mean QAC official plugins twice doesn't work?
Or do you mean, in a more general sense, that cleaning official plugins isn't working correctly, if those have been modified by other means before QAC?

**Comment by Superfly-Johnson** [comment]
> Can you explain the issue in more detail? What exactly do you mean by "patched ESMs"?
> 
> Do you mean QAC official plugins twice doesn't work? Or do you mean, in a more general sense, that cleaning official plugins isn't working correctly, if those have been modified by other means before QAC?

Yeah sorry,

Basically if you use a mod like the [unofficial esm patcher](https://www.nexusmods.com/fallout3/mods/25717/), you'll end up finding ITMs where there aren't any while cleaning mods, and you'll also often skip real ITMs.

I imagine the same also apply for Fallout New Vegas. Those mods essentially remove redundent content in the ESMs and change worldspace flags, but this may cause ITMs to be skipped.

**Comment by pStyl3** [comment]
I think that this might be out of scope for LOOT, plus the difficulty of writing a solid & future-proof condition for such a message doesn't make it any better.

If we wanted to create such a message, the easiest way would likely be to use the base game checksums for the condition, and if they aren't matched, display the message. But that would mean that each time a game get's updated, those checksums would need to be updated within the condition for this singular message, which would be a tedious work.

Using the checksums of cleaned base game files, or patched files (using the above linked patcher, or some other patcher) -- seems even less reasonable to me.

LOOT displays cleaning messages, if for dirty plugins these messages are manually added to the masterlist. Within those messages we link to a xEdit cleaning guide - [Link](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods) - I think that is enough for LOOT.

As such, I'm closing this issue as not planned.
