### ISSUE TITLE
Translate 'Delete. Already included or otherwise fixed in Unofficial Fallout 3 Patch.esm.'

### ISSUE THREAD

**Issue by Freso** [loot/fallout3#5]
I've changed the `*AlreadyInUF3P` string a bit to make it a bit more general for "patch mods" that are not included per se but whose fixes are still used in UF3P.

**Comment by pStyl3** [comment]
The russian translation by `Kerber` is as follows:
`Удалите. Уже включено в Unofficial Fallout 3 Patch.esm или исправлено иным образом.`

**Comment by pStyl3** [comment]
The spanish translation by `Artaios` is as follows:
`Borrar. Esta incluido o de otro modo fijo en Unofficial Fallout 3 Patch.esm.`

Edit:
The translation was further improved by native speaker `Mr. Robo to` to be:
`Borrar. Esta incluido, o de otra modo, arreglado en el Unofficial Fallout 3 Patch.esm`
