### ISSUE TITLE
Fallout 3 GOTY - Could not load cef_extensions.pak 

### ISSUE THREAD

**Issue by Andy1233** [loot/fallout3#78]
I don't understand what is happening or what this means. I'm a noob to the LOOT correctional software. Thanks

**Comment by Ortham** [comment]
It's harmless, ignore it.

**Comment by Andy1233** [comment]
I cant apply changes because of it

**Comment by Ortham** [comment]
If you can't apply changes, something else is going wrong. Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Andy1233** [comment]
I agree, that something else is wrong. But this seems to be the only error to report that I can find.

**Comment by Ortham** [comment]
Well, I can only help if you post your debug logs.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
