### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/fallout3#81]
I would like to relicense the LOOT masterlists/repositories to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit them to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

@WrinklyNinja, @Sharlikran, @SilentSpike, @CptMcSplody (these are [all the contributors listed on GitHub](https://github.com/loot/fallout3/graphs/contributors)) if you agree with moving to this much more free license, please write a comment here confirming this.

~~@WrinklyNinja If you're able to get a list of BOSS contributors prior to the conversion that haven't been mentioned above, that'd be great. :)~~

<details>
<summary>Agreed LOOT contributors</summary>

- [x] @Freso
- [x] @WrinklyNinja
- [x] @Sharlikran
- [x] @SilentSpike a.k.a. kymckay
- [x] @CptMcSplody
- [x] @sibir-ine 
- [x] @Infernio 
- [x] @DaCoolX 
- [x] LuthienKess `<luthien_kess at yahoo.com>`
</details>

<details>
<summary>Agreed BOSS contributors not already mentioned</summary>

- [x] @valda
- [x] @Arthmoor
- [x] @TokcDK
- [x] @deathssoul
- [x] @spaceoden
- [x] @NickDickinsonWilde
- [x] @mosanger
- [x] ~~A P Wade77 `<a.p.wade77 at gmail.com>`~~ Clean-room reimplemented contributions
- [x] ~~maahaa12 `<maahaa12 at gmail.com>`~~ Clean-room reimplemented contributions
- [x] ~~Torrello `<torrello.boss at gmail.com>` ([Nexus](https://www.nexusmods.com/users/2018867))~~ #319
</details>

Once/if everyone accepts, I'll change the license.

**Comment by Ortham** [comment]
The BOSS contributors not mentioned above are:

- @valida
- @Arthmoor
- @mosanger
- @NickWilde1990

Also the following people who I haven't been able to find on GitHub:

```
Torrello <torrello.boss@gmail.com>
Space Oden69 <jacksonleist@gmail.com>
maahaa12 <maahaa12@gmail.com>
Psymon <simon888@cox.net>
deaths_soul (MCP) <NULL>
A P Wade77 <a.p.wade77@gmail.com>
menduki <menduki@yandex.ru>
```

**Comment by Arthmoor** [comment]
No problem with this.

**Comment by Ortham** [comment]
I agree.

**Comment by MacSplody** [comment]
I agree.

**Comment by kymckay** [comment]
I agree.

**Comment by Sharlikran** [comment]
+1

**Comment by deathssoul** [comment]
CC0 is fine by me for the metadata: https://github.com/loot/oblivion/issues/24#issuecomment-410244509

:)

**Comment by Freso** [comment]
@spaceoden gave permission here: https://github.com/loot/loot.github.io/issues/61#issuecomment-410348382

**Comment by pStyl3** [comment]
@TokcDK agreed for Skyrim's and Oblivion's masterlist. I've ticked his checkbox for Fallout 3 aswell.

**Comment by pStyl3** [comment]
@valida
@mosanger
@NickWilde1990 @NickDickinsonWilde

Sorry to ping you again, but if time permits, could you evaluate the above mentioned situation?
Thank you.

**Comment by sibir-ine** [comment]
@Ortham Is valida supposed to be valda?

**Comment by Ortham** [comment]
Almost certainly yes, the name valida doesn't ring any bells.

**Comment by sibir-ine** [comment]
@valda Could you please take a look at the issue & comment whether you agree or disagree? You've agreed on the other masterlists, but, if you're still around, we'd like your explicit approval if we can get it.

**Comment by valda** [comment]
I agree😃

**Comment by sibir-ine** [comment]
> I agree😃

@valda Awesome, thanks for replying!

**Comment by sibir-ine** [comment]
Infernio agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817335752 (posting to keep track).

**Comment by sibir-ine** [comment]
@shadowslasher410 agreed in https://github.com/loot/fallout4/issues/42#issuecomment-313950643 & stated that we should change the license for every masterlist, so I think we can take that as approval for this one.

**Comment by sibir-ine** [comment]
DaCoolX agreed in https://github.com/loot/skyrim/issues/196#issuecomment-817339754.

**Comment by sibir-ine** [comment]
@mosanger @NickDickinsonWilde

If you guys are still around, could you please read this issue & state whether you agree?

**Comment by Ortham** [comment]
Here are links to view the outstanding BOSS contributors' contributions (in the BOSS masterlist):

- [Torrello](https://github.com/boss-developers/fallout3/commits/master?author=torrello.boss@gmail.com): 5 pages of commits ([TODO](https://gist.github.com/sibir-ine/5fbf24b027a2318488f2c02ac96a22cd))
- [maahaa12](https://github.com/boss-developers/fallout3/commits/master?author=maahaa12@gmail.com): 1 page of commits ([TODO](https://gist.github.com/sibir-ine/b7f3b34e1afaca5fa422201dcb8ece54))
- ~~[mosanger](https://github.com/boss-developers/fallout3/commits/master?author=mosanger): 2 pages of commits~~ Agreed
- ~~[NickDickinsonWilde](https://github.com/boss-developers/fallout3/commits/master?author=NickDickinsonWilde): 1 page of commits~~ Agreed
- ~~[A P Wade77](https://github.com/boss-developers/fallout3/commits/master?author=a.p.wade77@gmail.com): 2 commits~~ Clean-room reimplemented contributions, agreement not required

**Comment by Infernio** [comment]
Re: A P Wade77, only one of [their changes](https://github.com/boss-developers/fallout3/compare/26f9975917369faac61353e0fd4271d45e7a2be9...92196dcdbc60d9d1f46d6f08c25aea053c995801) is *arguably* in the masterlist: The information that Easier_hacking_5_8.esp shouldn't be used together with Lucky_hacking_5.esp.

https://github.com/loot/fallout3/blob/66109177c0d78361673acb264384958b43af2eda/masterlist.yaml#L4559-L4562

**Comment by sibir-ine** [comment]
> Re: A P Wade77, only one of [their changes](https://github.com/boss-developers/fallout3/compare/26f9975917369faac61353e0fd4271d45e7a2be9...92196dcdbc60d9d1f46d6f08c25aea053c995801) is _arguably_ in the masterlist: The information that Easier_hacking_5_8.esp shouldn't be used together with Lucky_hacking_5.esp.

The plugins still exist, so I added a location in #230. I also replaced the `inc` entries with a more appropriate `*useOnlyOneX` message, though it is closer to what A P Wade77 originally submitted. ~~If we don't want to count my changes as sufficiently replacing their contributions with my own, the mod is pretty ancient. However, people still seem to be actively using it, so hopefully A P responds. @Ortham Can we count my change as sufficiently replacing A P's contribution in this case?~~

Considering that I've clean-room reimplemented the entry, I think it's safe to say we don't need their agreement anymore. I'll keep them listed with a note in case they do get back to us at some point.

**Comment by sibir-ine** [comment]
NickDickinsonWilde agreed in https://github.com/loot/loot.github.io/issues/61#issuecomment-817452568.

**Comment by sibir-ine** [comment]
LuthienKess agreed via email:

> I agree with the license change for all my contributions.

**Comment by mosanger** [comment]
> @valida
> @mosanger
> @NickWilde1990 @NickDickinsonWilde
> 
> Sorry to ping you again, but if time permits, could you evaluate the above mentioned situation?
> Thank you.

sorry, sure, please go ahead!
although I seem to be too late anyway :D

**Comment by sibir-ine** [comment]
> although I seem to be too late anyway

@mosanger You're not too late. Thank you so much for responding!
